### ISSUE TITLE
🤔 学校网站上怎么查看自己填没填？

### ISSUE THREAD

**Issue by RealKai42** [zhangt2333/actions-SduHealthReport#2]
RT

**Comment by sdu-gyf** [comment]
在山东大学 服务大厅 看办结事项

**Comment by zhangt2333** [comment]
在 https://scenter.sdu.edu.cn/ 登录后，直接访问 https://scenter.sdu.edu.cn/tp_fp/view?m=fp#act=fp/myserviceapply/indexFinish 即可看到
